### ISSUE TITLE
findElement fails on first test even though though the element is visible and on second test it passes at exact same step

### ISSUE THREAD

**Issue by gavrildg2** [Perfecto-Quantum/Quantum-Starter-Kit#29]
I have a test where  I launch an app and then i check if the element //*[@text='Messages'] is visible but it fails even though the element is visible, xpath is checked and after it moves to second test which starts the same way it will pass and move to next steps. This was working on last test done on perfecto instance 10.10 but it stopped on 10.12 version.
Any idea what might be the issue?
 
Assert.assertTrue(launchAndroidMessagesApp(senderDevice));
Assert.assertTrue(homeScreen.messagesHeaderDisplayed(senderDevice));

 
 
[Pixel2 HT7731A0]: ▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://rogers.reporting.onsite.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_51_25009&_timestamp[0]=1513885851688, eclipseExecutionId=gavrildg@amdocs.com_Eclipse_17-12-21_11_18_59_24940, available=false, language=English, deviceName=HT7731A00770, deviceId=HT7731A00770, resolution=1080x1920, platform=ANY, wifiMacAddress=40:4e:36:0b:5b:ab, manufacturer=Google, mode=CONNECTED, password=, cradleId=HSS-106/VIRTUAL/01, osVersion=8.1.0, host=rogers.onsite.perfectomobile.com, singleTestReportUrl=https://rogers.onsite.perfectomobile.com/nexperience/singletest/report/?reportRepositoryKey=PRIVATE:RemoteWebDriver/171221/RemoteWebDriver_17-12-21_14_50_51_25009.xml&ownerId=gavrildg@amdocs.com&sharingCode=a05ff647-9c2f-4323-8a3e-ccb64481631e, inUse=true, takesScreenshot=true, javascriptEnabled=true, model=Pixel 2, firmware=walleye-userdebug 8.1.0 OPM1.171019.011 4448085 dev-keys, rotatable=true, testGridReportUrl=https://rogers.reporting.onsite.perfectomobile.com?externalId[0]=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_51_25009&_timestamp[0]=1513885851688, os=Android, entityType=remote_web_driver, allocatedTo=gavrildg@amdocs.com, serverConnector=, securityToken=, executionId=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_51_25009, phoneNumber=+16479240083, webdriver.remote.sessionid=043d5fba-0a98-49f7-84b8-19da3a019cf0, locationContextEnabled=true, scriptName=RemoteWebDriver, location=Toronto, linkType=lab, reportKey=PRIVATE:RemoteWebDriver/171221/RemoteWebDriver_17-12-21_14_50_51_25009.xml, windTunnelReportUrl=https://rogers.onsite.perfectomobile.com/nexperience/singletest/report/?reportRepositoryKey=PRIVATE:RemoteWebDriver/171221/RemoteWebDriver_17-12-21_14_50_51_25009.xml&ownerId=gavrildg@amdocs.com&sharingCode=a05ff647-9c2f-4323-8a3e-ccb64481631e, user=, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected}] ▀▄▀▄▀
[Pixel2 HT7731A0]: Executing setTimeout parameters: {"ms":0,"type":"implicit"} 
[Pixel2 HT7731A0]: command: setTimeout[ param-1: {type=implicit, ms=0}] Result: null 
driver init done
[Pixel2 HT7731A0]: Executing switchToContext parameters: {"name":"NATIVE_APP"} 
[Pixel2 HT7731A0]: command: switchToContext[ param-1: {name=NATIVE_APP}] Result: null 
[Pixel2 HT7731A0]: Executing executeScript parameters: {"args":[{"identifier":"com.google.android.apps.messaging"}],"script":"mobile:application:close"} 
[Pixel2 HT7731A0]: Executing executeScript parameters: {"args":[{"identifier":"com.google.android.apps.messaging"}],"script":"mobile:application:open"} 
[Pixel2 HT7731A0]: Executing findElement parameters: {"using":"xpath","value":"//*[@text='Messages']"} 
[Pixel2 HT7731A0]: amdocs.com&sharingCode=10f938cd-8769-40b4-a87b-5acdf142f306, user=, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected}]
Session ID: 2bc0a041-ae05-4da5-b533-8063d2ddf5a8
*** Element info: {Using=xpath, value=//*[@text='Messages']} 
org.openqa.selenium.TimeoutException: Timed out after 30 seconds waiting for presence of element located by: By.xpath: //*[@text='Messages']
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GAVRILDG02', ip: '10.16.34.99', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: QAFExtendedWebDriver
at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:292)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.load(QAFExtendedWebDriver.java:214)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.load(QAFExtendedWebElement.java:284)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.getId(QAFExtendedWebElement.java:294)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.isDisplayed(QAFExtendedWebElement.java:314)
at com.rogers.apps.custom.android_messages.screens.genericGooglePixel.HomeScreen.messagesHeaderDisplayed(HomeScreen.java:54)
at com.rogers.apps.custom.android_messages.steps.GenericSteps.sendMMSImageGallery(GenericSteps.java:96)
at com.rogers.utils.DecisionMaker.appAndroidMessagesSendMMSImageGallery(DecisionMaker.java:23)
at com.rogers.tests.Sanity.appAndroidMessagesSendAndReceiveMMS(Sanity.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:781)
at org.testng.TestRunner.run(TestRunner.java:635)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
at org.testng.SuiteRunner.run(SuiteRunner.java:289)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
at org.testng.TestNG.runSuites(TestNG.java:1133)
at org.testng.TestNG.run(TestNG.java:1104)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.openqa.selenium.NoSuchElementException: Element with by xpath '//*[@text='Messages']' wasn't found.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'MCM-ROGERS', ip: '192.168.100.10', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: driver.version: EventFiringWebDriver
Command duration or timeout: 61.17 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GAVRILDG02', ip: '10.16.34.99', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver
Capabilities [{reportPdfUrl=https://rogers.reporting.onsite.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_37_25007&_timestamp[0]=1513885837895, eclipseExecutionId=gavrildg@amdocs.com_Eclipse_17-12-21_11_18_59_24940, available=false, language=English, deviceName=1115FB434A041E03, deviceId=1115FB434A041E03, resolution=1440x2560, platform=ANY, wifiMacAddress=24:4b:03:83:f3:68, manufacturer=Samsung, mode=CONNECTED, password=, cradleId=HSS-204/007282/01, osVersion=7.0, automationName=Appium, host=rogers.onsite.perfectomobile.com, singleTestReportUrl=https://rogers.onsite.perfectomobile.com/nexperience/singletest/report/?reportRepositoryKey=PRIVATE:RemoteWebDriver/171221/RemoteWebDriver_17-12-21_14_50_37_25007.xml&ownerId=gavrildg@amdocs.com&sharingCode=10f938cd-8769-40b4-a87b-5acdf142f306, inUse=true, takesScreenshot=true, browserName=MobileOS, javascriptEnabled=true, model=Galaxy S6, firmware=zerofltebmc-user 7.0 NRD90M G920W8VLU5DQD4 release-keys, rotatable=true, testGridReportUrl=https://rogers.reporting.onsite.perfectomobile.com?externalId[0]=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_37_25007&_timestamp[0]=1513885837895, os=Android, entityType=remote_web_driver, allocatedTo=gavrildg@amdocs.com, serverConnector=, securityToken=, executionId=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_37_25007, webdriver.remote.sessionid=2bc0a041-ae05-4da5-b533-8063d2ddf5a8, locationContextEnabled=true, scriptName=RemoteWebDriver, location=Toronto, linkType=lab, reportKey=PRIVATE:RemoteWebDriver/171221/RemoteWebDriver_17-12-21_14_50_37_25007.xml, windTunnelReportUrl=https://rogers.onsite.perfectomobile.com/nexperience/singletest/report/?reportRepositoryKey=PRIVATE:RemoteWebDriver/171221/RemoteWebDriver_17-12-21_14_50_37_25007.xml&ownerId=gavrildg@amdocs.com&sharingCode=10f938cd-8769-40b4-a87b-5acdf142f306, user=, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected}]
Session ID: 2bc0a041-ae05-4da5-b533-8063d2ddf5a8
*** Element info: {Using=xpath, value=//*[@text='Messages']}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:234)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElementByXPath(QAFExtendedWebDriver.java:398)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElementByXPath(QAFExtendedWebDriver.java:1)
at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElement(QAFExtendedWebDriver.java:169)
at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElement(QAFExtendedWebDriver.java:1)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:899)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:181)
at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:178)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
... 33 more
Caused by: org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GAVRILDG02', ip: '10.16.34.99', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: QAFExtendedWebDriver
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:138)
... 48 more
Caused by: org.openqa.selenium.NoSuchElementException: Element with by xpath '//*[@text='Messages']' wasn't found.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'MCM-ROGERS', ip: '192.168.100.10', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: driver.version: EventFiringWebDriver
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GAVRILDG02', ip: '10.16.34.99', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: EventFiringWebDriver
at com.perfectomobile.selenium.MobileApplication.getSingleElement(MobileApplication.java:339)
at com.perfectomobile.selenium.MobileApplication.findElementByXPath(MobileApplication.java:194)
at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
at com.perfectomobile.selenium.MobileApplication.findElement(MobileApplication.java:133)
at com.perfectomobile.selenium.server.PerfectoMobileDriver.findElement(PerfectoMobileDriver.java:825)
at sun.reflect.GeneratedMethodAccessor1384.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:104)
at com.sun.proxy.$Proxy263.findElement(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:188)
at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:33)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.openqa.selenium.remote.server.MobileDefaultSession.lambda$execute$0(MobileDefaultSession.java:187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[Pixel2 HT7731A0]: java.lang.AssertionError: expected [true] but found [false] 
[Pixel2 HT7731A0]: Executing screenshot parameters: {} 
[Pixel2 HT7731A0]: Capturing screen shotappAndroidMessagesSendAndReceiveMMS_1snqfdecw1w4x22508.png 
[Pixel2 HT7731A0]: at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)\r\n"}],"script":"mobile:test:end"} 
[Pixel2 HT7731A0]: ▀▄▀▄▀ REPORTIUM URL: https://rogers.reporting.onsite.perfectomobile.com?externalId%5B0%5D=gavrildg@amdocs.com_RemoteWebDriver_17-12-21_14_50_37_25007&_timestamp%5B0%5D=1513885837895 ▀▄▀▄▀
[Pixel2 HT7731A0]: █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
[Pixel2 HT7731A0]: █ TEST FAILED: appAndroidMessagesSendAndReceiveMMS [{textMMS=MMS Flow test -This is MMS no 1}] █
[Pixel2 HT7731A0]: █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

**Comment by gavrildg2** [comment]
Any suggestions?

**Comment by kulin24** [comment]
This is probably too late, but I would suggest you to wait for some time before initializing your page object. 
I would like to see the selenium code that you have implemented.
