### ISSUE TITLE
afterTest fails for more than two iterations in quantum version 1.13-RC1

### ISSUE THREAD

**Issue by gavrildg2** [Perfecto-Quantum/Quantum-Starter-Kit#34]
Hi,

Using the latest pom (with <quantum.version>1.13-RC1</quantum.version>) I'm getting below exception when I have to execute a test in more than 2 iterations. The actual tests are fine but the end result fails because of this exception on afterTest.
The same tests were executed with success in old pom (with <quantum.version>1.11</quantum.version>). 

main: Executing quit parameters: {} 
main: command: quit[ param-1: {}] Result: null 
main: UI-driver tear down complete... 
main: java.lang.NullPointerException 
main: Executing screenshot parameters: {} 
main: d5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GAVRILDG02', ip: '10.16.40.145', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_162'
Driver info: driver.version: QAFExtendedWebDriver 
org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GAVRILDG02', ip: '10.16.40.145', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_162'
Driver info: driver.version: QAFExtendedWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:134)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:224)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.getScreenshotAs(QAFExtendedWebDriver.java:272)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.takeScreenShot(QAFExtendedWebDriver.java:464)
	at com.qmetry.qaf.automation.core.QAFTestBase.takeScreenShot(QAFTestBase.java:356)
	at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener.processResult(QAFTestNGListener.java:289)
	at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener.afterInvocation(QAFTestNGListener.java:211)
	at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener2.afterInvocation(QAFTestNGListener2.java:158)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithContextStrategy.callMethod(InvokedMethodListenerInvoker.java:108)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithContextStrategy.callMethod(InvokedMethodListenerInvoker.java:104)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:557)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:536)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:1008)
	at org.testng.TestRunner.run(TestRunner.java:639)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Preparing For Shut Down...
Thread-0: Executing quit parameters: {} 
Thread-0: command: quit[ param-1: {}] Result: null 
Thread-0: UI-driver tear down complete... 
Exception in thread "Thread-0" java.lang.NullPointerException
	at com.qmetry.qaf.automation.core.QAFTestBase.tearDown(QAFTestBase.java:191)
	at com.qmetry.qaf.automation.core.TestBaseProvider.stopAll(TestBaseProvider.java:69)
	at com.qmetry.qaf.automation.core.TestBaseProvider$1.run(TestBaseProvider.java:97)

**Comment by kulin24** [comment]
We are planning to have this bug fixed in the next release.
