### ISSUE TITLE
Json file contains ":" in content would get JsonSyntaxException

### ISSUE THREAD

**Issue by MoonLikeSinging** [Perfecto-Quantum/Quantum-Starter-Kit#48]
### quantum.version
<quantum.version>1.20.1</quantum.version>

### Steps To Reproduce
    1.  Use above test data in feature as test file

### Expected behavior
I can get the content in test successfully.

### Actual behavior
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 67 path $.[2]

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
[
  {
    "waitTimeToReceiveEmail": "5",
    "emailContent" : {
      "sender" : "test@test.com",
      "title": "test",
      "content" : ["休假申请已被批准", "业务流程：短期休假申请:moon"]
    }
  }
]
>### Feature file
    Then User can validate email content with "<emailContent>"
    Examples: {'datafile':'./src/main/resources/data/test.json'}

### Note:
I use Gson to get the content, it's worked well.
JsonParser.parseReader(new FileReader("test.json"))

**Comment by MoonLikeSinging** [comment]
Please refer to https://github.com/qmetry/qaf/issues/340 to see the details.
After testing, it's only occurred on quantum not qaf.

**Comment by MoonLikeSinging** [comment]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 67 path $.[2]

	at .When Then User can validate email content with "${emailContent}"(src/main/resources/scenarios/test.feature:5)
	at com.google.gson.Gson.fromJson(Gson.java:937)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:836)
	at com.google.gson.Gson.fromJson(Gson.java:808)
	at com.quantum.listeners.QuantumReportiumListener.getProcessStepDescription(QuantumReportiumListener.java:610)
	at com.quantum.listeners.QuantumReportiumListener.beforExecute(QuantumReportiumListener.java:249)
	at com.qmetry.qaf.automation.step.BaseTestStep.beforExecute(BaseTestStep.java:177)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:143)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:126)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 67 path $.[2]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:60)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:922)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:836)
	at com.google.gson.Gson.fromJson(Gson.java:808)
	at com.quantum.listeners.QuantumReportiumListener.getProcessStepDescription(QuantumReportiumListener.java:610)
	at com.quantum.listeners.QuantumReportiumListener.beforExecute(QuantumReportiumListener.java:249)
	at com.qmetry.qaf.automation.step.BaseTestStep.beforExecute(BaseTestStep.java:177)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:143)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:126)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	... 4 more

**Comment by MoonLikeSinging** [comment]
This bug is caused by QuantumReportiumListener,  in QuantumReportiumListener.class, when the string contains ':' in the string , then this step ```Map<String, Object> kv = (Map)(new Gson()).fromJson(pstr, Map.class)``` would get this exception.

**Comment by ksitwala-perfecto** [comment]
I tried with the latest Quantum Starter kit and it works for the following details:

[
{
"waitTimeToReceiveEmail": "5",
"emailContent" : {
"sender" : "test@test.com",
"title": "test",
"content" : ["休假申请已被批准", "业务流程：短期休假申请:moon"]
}
}
]

  @appium @SampleTest
  Scenario Outline: Appium Example
    Given I start application by name "Calculator"
    And I pass parameter with colon "<emailContent>"
	Examples: {'datafile':'src/main/resources/data/testdata.json'}

Logs of execution - 
[iPhone.* 0C2210]: ▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://ps.app.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=kulins@perfectomobile.com_RemoteWebDriver_20-05-20_08_37_33_1349&_timestamp[0]=1589963853175, statBarHeight=20, simpleIsVisibleCheck=true, viewportRect={top=60, left=0, width=1242, height=2148}, streamInfo={"url":"https://ps.perfectomobile.com/services/v2.0/devices/0C2210C8EBD9A1FB421A8D0A692E6C72F85E4C9E/screenshot?executionId=kulins@perfectomobile.com_RemoteWebDriver_20-05-20_08_37_33_1349&cloud=ps-perfectomobile-com&fixedSize=700","type":"IMAGE_MODE","httpMethod":"GET","authenticationType":"PERFECTO_PARAMETER"}, CFBundleIdentifier=com.apple.mobilesafari, deviceName=0C2210C8EBD9A1FB421A8D0A692E6C72F85E4C9E, platform=IOS, cloud=ps.perfectomobile.com, password=, deviceSessionId=77a0423e-0f1a-4f60-92fa-b5454917ff7f, driverClass=io.appium.java_client.ios.IOSDriver, liveStreamEnabled=false, platformVersion=13.4.1, automationName=Appium, host=ps.perfectomobile.com, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, model=iPhone.*, assert_javascript_enabled=true, udid=0c2210c8ebd9a1fb421a8d0a692e6c72f85e4c9e, platformName=IOS, applicationName=Calculator, stopUrl=https://ps.perfectomobile.com/nexperience/perfectomobile/wd/hub/session/77a0423e-0f1a-4f60-92fa-b5454917ff7f, testGridReportUrl=https://ps.app.perfectomobile.com/reporting/library?externalId[0]=kulins@perfectomobile.com_RemoteWebDriver_20-05-20_08_37_33_1349&_timestamp[0]=1589963853175, entityType=remote_web_driver, xcuitestFindOptimizations=true, accessToken=eyJhbGciOiJSUzI1NiIsInR5cCIgO..., serverConnector=, serverHost=100.94.13.110:11602, securityToken=, executionId=kulins@perfectomobile.com_RemoteWebDriver_20-05-20_08_37_33_1349, webdriver.remote.sessionid=77a0423e-0f1a-4f60-92fa-b5454917ff7f, pixelRatio=3, authenticationTenant=operator, scriptName=RemoteWebDriver, sdkVersion=13.4.1, device=iphone, executionTenantId=ps-perfectomobile-com, user=, cssSelectorsEnabled=true}] ▀▄▀▄▀
[iPhone.* 0C2210]: Executing setTimeout parameters: {"implicit":0} 
[iPhone.* 0C2210]: command: setTimeout[ param-1: {implicit=0}] Result: null 
[iPhone.* 0C2210]: driver init done 
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{"customFields":[],"name":"Appium Example","projectName":"Quantum-Starter-Kit","projectVersion":"1.0","tags":["IOS Calc Test","Appium Demo Suite","@appium","@SampleTest"]}],"script":"mobile:test:start"} 
[iPhone.* 0C2210]: █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
[iPhone.* 0C2210]: █ TEST STARTED: Appium Example [{waitTimeToReceiveEmail=5, emailContent={sender=test@test.com, title=test, content=[休假申请已被批准, 业务流程：短期休假申请:moon]}}] █
[iPhone.* 0C2210]: █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
[]
[iPhone.* 0C2210]: ▄ ▄ ▄ BEGIN STEP: Given I start application by name "Calculator" ▄ ▄ ▄
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{"name":"Given I start application by name \"Calculator\""}],"script":"mobile:step:start"} 
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{"name":"Calculator"}],"script":"mobile:application:open"} 
[iPhone.* 0C2210]: Executing switchToContext parameters: {"name":"NATIVE_APP"} 
[iPhone.* 0C2210]: command: switchToContext[ param-1: {name=NATIVE_APP}] Result: null 
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{}],"script":"mobile:step:end"} 
[iPhone.* 0C2210]: ▀ ▀ ▀ END STEP: Given I start application by name "Calculator" ▀ ▀ ▀
[{emailContent}]
[iPhone.* 0C2210]: ▄ ▄ ▄ BEGIN STEP: And I pass parameter with colon "{sender=test@test.com, title=test, content=[休假申请已被批准, 业务流程：短期休假申请:moon]}" ▄ ▄ ▄
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{"name":"And I pass parameter with colon \"{sender=test@test.com, title=test, content=[休假申请已被批准, 业务流程：短期休假申请:moon]}\""}],"script":"mobile:step:start"} 
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{}],"script":"mobile:step:end"} 
[iPhone.* 0C2210]: ▀ ▀ ▀ END STEP: And I pass parameter with colon "{sender=test@test.com, title=test, content=[休假申请已被批准, 业务流程：短期休假申请:moon]}" ▀ ▀ ▀
[iPhone.* 0C2210]: ：短期休假申请:moon]}]\nat \n\tat .And I pass parameter with colon \"${emailContent}\"(src/main/resources/scenarios/appiumCalc.feature:8)\n\tat com.quantum.steps.CalcStepsDefs.passParameter(com.quantum.steps.CalcStepsDefs:0)\n"}],"script":"mobile:test:end"} 
[iPhone.* 0C2210]: ▀▄▀▄▀ REPORTIUM URL: https://ps.app.perfectomobile.com/reporting/library?externalId%5B0%5D=kulins@perfectomobile.com_RemoteWebDriver_20-05-20_08_37_33_1349&_timestamp%5B0%5D=1589963853175 ▀▄▀▄▀
[iPhone.* 0C2210]: █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
[iPhone.* 0C2210]: █ TEST FAILED: Appium Example [{waitTimeToReceiveEmail=5, emailContent={sender=test@test.com, title=test, content=[休假申请已被批准, 业务流程：短期休假申请:moon]}}] █
[iPhone.* 0C2210]: █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
[iPhone.* 0C2210]: Executing quit parameters: {} 
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{"name":"Calculator"}],"script":"mobile:application:close"} 
[iPhone.* 0C2210]: Executing executeScript parameters: {"args":[{}],"script":"mobile:execution:close"}

**Comment by ksitwala-perfecto** [comment]
Please share your step definition code. The issue is not reproducible on our end with different parameter types. (String & Map) 
There is no error on execution.

**Comment by MoonLikeSinging** [comment]
@Then("^User can validate email content with \"([^\"]*)\"$")
    public void userCanValidateEmailContentWith(Object emailContent){

        System.out.println("**********" + emailContent.toString());
        JsonParser jsonParser = new JsonParser();

        JsonObject emailContentNode = jsonParser.parse(emailContent.toString()).getAsJsonObject();
        String sender = emailContentNode.get("sender").getAsString();


        //Filter unread email
        new QAFExtendedWebElement(FILTER).click();
        new QAFExtendedWebElement(FILTER_UNREAD).click();

        //Click the new email to show content
        new QAFExtendedWebElement("\"//div[@role='listbox']//span[@title='" + sender + "']");
        String currentMailContents = new QAFExtendedWebElement(currentMailContent).getAttribute("innerHTML");
        System.out.println(currentMailContents);

        threadWait(100000);
    }

**Comment by MoonLikeSinging** [comment]
public static void main(String[] args) {
        try {
            String str = "{sender=test@test.com, title=test, content=[休假申请已被批准, 业务流程：短期休假申请:moon]}";
            Map<String, Object> kv = (Map)(new Gson()).fromJson(str, Map.class);

            System.out.println(kv);

        }catch (IOException ie){
            ie.printStackTrace();
        }
    }

@ksitwala-perfecto I just run this script, it's also get the exception, this part
```Map<String, Object> kv = (Map)(new Gson()).fromJson(str, Map.class);```
is in QuantumReportiumListener line 473.

**Comment by ksitwala-perfecto** [comment]
@MoonLikeSinging - 
Is it possible for you to use @QAFTestStep instead with the following syntax:

@QAFTestStep(description = "I pass parameter with colon {0}")
	public void passParameter(Map<String, String> value) {
		System.out.println("Passed parameter value -> " + value.keySet());
	}

This will serve you the similar purpose but will avoid the need to parse that json data.

**Comment by ksitwala-perfecto** [comment]
Also, the reason why we are getting this error is because the json converted string is not in json format and that is why the GSON parser is not able to parse it.

**Comment by MoonLikeSinging** [comment]
Thanks, I have try to use it, it's worked well.
 We use cucumber annotation because there is no plugins on intellij idea. It's not easy to skip from step to script.
