### ISSUE TITLE
Getting org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <

### ISSUE THREAD

**Issue by shibupanda** [Perfecto-Quantum/Quantum-Starter-Kit#63]
org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AZWVDPHEV1395', ip: '10.229.152.209', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_311'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:69) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:55) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.json.Json.toType(Json.java:50) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158) ~[selenium-remote-driver-3.141.59.jar:?]
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239) ~[java-client-7.3.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-remote-driver-3.141.59.jar:?]
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41) ~[java-client-7.3.0.jar:?]
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) ~[java-client-7.3.0.jar:?]
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) ~[java-client-7.3.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285) ~[selenium-remote-driver-3.141.59.jar:?]
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45) ~[java-client-7.3.0.jar:?]
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1) ~[java-client-7.3.0.jar:?]
	at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1) ~[java-client-7.3.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106) ~[selenium-remote-driver-3.141.59.jar:?]
	at com.manulife.ap.steps.common.CommonSteps.iLogInDTKApplicationiOS(CommonSteps.java:561) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150) ~[qaf-2.1.15.jar:?]
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:146) [qaf-2.1.15.jar:?]
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:126) [qaf-2.1.15.jar:?]
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174) [qaf-2.1.15.jar:?]
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:66) [qaf-2.1.15.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:778) [qaf-2.1.15.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [qaf-2.1.15.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) [testng-6.10.jar:?]
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39) [testng-6.10.jar:?]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421) [testng-6.10.jar:?]
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) [testng-6.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_311]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]

**Comment by kulin24** [comment]
Please share more details on the code used and the driver configuration. Unfortunately, the exception alone is not enough to provide any suggestion.
