### ISSUE TITLE
Not able to execute test in Parallel

### ISSUE THREAD

**Issue by NanthaKumarPalanaiappan** [Perfecto-Quantum/Quantum-Starter-Kit#64]
While trying to run Parallel execution.  The last test only getting executed.

I have updated 3 test for Parallel execution. If I running the below xml file, Driver instance not created for Test1 & Test2 and geting failed but Test3 only getting executed.

Note: If executed sequentially all scripts  are working fine.

Please help me on this. I need to execute Scenarios parallelly in edge browser.

XML
<suite name="Credits"  verbose="0" parallel="tests" thread-count="4">
	<test name="Test1" enabled="true"  >
		<parameter name="driver.name" value="edgeDriver"></parameter>
		<groups>
			<run>
				<include name="@Test1" />
			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
	<test name="Test2" enabled="true"  >
		<parameter name="driver.name" value="edgeDriver"></parameter>
		<groups>
			<run>
				<include name="@Test2" />
			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
<test name="Test3" enabled="true"  >
		<parameter name="driver.name" value="edgeDriver"></parameter>
		<groups>
			<run>
				<include name="@Test3" />
			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
</suite>

Error Message
 com.qmetry.qaf.automation.core.AutomationError: Unable to Create Driver Instance for edge: null
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.standardConnect(UiDriverFactory.java:442)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.getDriver(UiDriverFactory.java:413)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.access$300(UiDriverFactory.java:282)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriver(UiDriverFactory.java:221)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.get(UiDriverFactory.java:89)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:568)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:1)
	at com.qmetry.qaf.automation.ui.util.DynamicWait.until(DynamicWait.java:147)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:478)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:253)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:44)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:1)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:81)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:88)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:65)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:61)
	at com.leedOnline.pages.OnlineCreditsFormPage.<init>(OnlinePage.java:28)
	at com.leedOnline.steps.OnlineCreditForms.<init>(OnlinePageDetails.java:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.qmetry.qaf.automation.step.DefaultObjectFactory.createInstance(DefaultObjectFactory.java:83)
	at com.qmetry.qaf.automation.step.DefaultObjectFactory.getObject(DefaultObjectFactory.java:60)
	at com.qmetry.qaf.automation.step.ObjectFactory$Provider.getObject(ObjectFactory.java:48)
	at com.qmetry.qaf.automation.step.JavaStep.getStepProvider(JavaStep.java:173)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:137)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:127)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:259)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.access$800(UiDriverFactory.java:73)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.standardConnect(UiDriverFactory.java:437)
	... 51 more

**Comment by ksitwala-perfecto** [comment]
Please share the XML file content again as it is not added and it will be great if you can share the entire console logs.

**Comment by ksitwala-perfecto** [comment]
Did you try keeping the driver.name property outside of the test node? If you are a Perfecto customer then please feel free to raise a support case.

**Comment by NanthaKumarPalanaiappan** [comment]
I have tried. But still same issue logs getting. If possible.. Could you please share me the sample project for Parallel execution for running it in edge browser.

**Comment by NanthaKumarPalanaiappan** [comment]
Hi 
The issue persist in Edgedriver only. Can you please take a look?
I have tried in chromedriver and its working fine.
